(function(){
const C=window.ECOS_CONSTANTS,E=window.Ecos;
const esc=E.esc;
function field(label,value,name,type='text',required=false){return `<div class="form-group"><label>${esc(label)}</label><input type="${type}" name="${esc(name)}" value="${esc(value)}"${required?' required':''}></div>`}
function area(label,value,name){return `<div class="form-group"><label>${esc(label)}</label><textarea name="${esc(name)}">${esc(value)}</textarea></div>`}
function select(label,value,name,options){return `<div class="form-group"><label>${esc(label)}</label><select name="${esc(name)}">${options.map(o=>`<option value="${esc(o)}"${String(value??'')===String(o)?' selected':''}>${esc(o)}</option>`).join('')}</select></div>`}
const labels={contratos:'Contrato',tecnicas:'Técnica',poderes:'Poder',fraquezas:'Fraqueza',resistencias:'Resistência',absorvidos:'Conceito Absorvido',itens:'Item'};
function row(group,item={},idx='new'){
 return `<div class="repeater-row" data-row="${esc(idx)}"><button type="button" class="repeater-remove" aria-label="Remover">✕</button>${C.REPEATER_FIELDS[group].map(([k,l,t])=>t==='textarea'?area(l,item[k],`${group}[${idx}][${k}]`):field(l,item[k],`${group}[${idx}][${k}]`)).join('')}</div>`;
}
function repeater(group,items=[]){return `<div id="rep_${group}">${items.map((x,i)=>row(group,x,i)).join('')}</div><button type="button" class="repeater-add" data-add="${group}">+ Adicionar ${labels[group]}</button>`}
function numeric(title,keys,data,prefix){return `<div class="form-section"><h4>${title}</h4><div class="form-row attr-grid">${keys.map(k=>`<div class="form-group"><label>${k}</label><input type="number" name="${prefix}[${k}]" value="${esc(data?.[k]??'')}"></div>`).join('')}</div></div>`}
function imageSection(f,label){return `<div class="form-section"><h4>Imagem</h4>${f.imagem?`<img src="${esc(f.imagem)}" class="ficha-img" alt="Imagem atual">`:''}<label>${label}</label><input id="imagem" type="file" accept="image/jpeg,image/png,image/gif,image/webp"></div>`}
function weaponOptions(selected){return C.ARMAS.map(a=>`<option value="${esc(a.nome)}" data-dano="${esc(a.dano)}"${selected===a.nome?' selected':''}>${esc(a.nome)}${a.dano?` (${a.dano})`:''}</option>`).join('')}
function hunterForm(f={},users=[],submit='SALVAR FICHA',edit=false){
 const i=f.info||{},a=f.atributos||{},r=f.recursos||{},p=f.pericias||{},eq=f.equipamentos||{},ch=f.caracteristicas||{};
 const items=(eq.itens||[]).map(nome=>({nome}));
 return `<form id="fichaForm" data-tipo="hunter">
 <div class="form-section"><h4>Vínculo</h4><label>Usuário dono da ficha</label><select name="usuario_id"><option value="">Sem vínculo</option>${users.map(u=>`<option value="${esc(u.id)}"${String(f.usuario_id??'')===String(u.id)?' selected':''}>${esc(u.usuario||'Usuário')}</option>`).join('')}</select></div>
 ${imageSection(f,'Foto do Hunter')}
 <div class="form-section"><h4>Informações básicas</h4><div class="form-row">${field('Nome',i.nome,'info[nome]','text',true)}${field('Apelido',i.apelido,'info[apelido]')}${field('Idade',i.idade,'info[idade]')}${field('Sexo',i.sexo,'info[sexo]')}${field('Altura',i.altura,'info[altura]')}${field('Organização',i.organizacao,'info[organizacao]')}${select('Rank',i.rank,'info[rank]',C.RANKS)}${field('Ocupação',i.ocupacao,'info[ocupacao]')}</div></div>
 ${numeric('Atributos',C.ATTRS,a,'atributos')}${numeric('Recursos',['HP','SP','CP','DEF','MOV'],r,'recursos')}
 <div class="form-section"><h4>Perícias</h4><div class="skill-check">${C.PERICIAS.map(x=>`<label><input type="checkbox" name="pericias[${esc(x)}]"${p[x]?' checked':''}> ${esc(x)}</label>`).join('')}</div></div>
 <div class="form-section"><h4>Contratos</h4>${repeater('contratos',f.contratos||[])}</div><div class="form-section"><h4>Técnicas próprias</h4>${repeater('tecnicas',f.tecnicas||[])}</div>
 <div class="form-section"><h4>Equipamentos</h4><div class="form-row"><div class="form-group"><label>Arma principal</label><select id="armaPrincipal" name="equipamentos[arma_principal][nome]">${weaponOptions(eq.arma_principal?.nome)}</select></div>${field('Dano',eq.arma_principal?.dano,'equipamentos[arma_principal][dano]')}<div class="form-group"><label>Arma secundária</label><select id="armaSecundaria" name="equipamentos[arma_secundaria][nome]">${weaponOptions(eq.arma_secundaria?.nome)}</select></div>${field('Dano',eq.arma_secundaria?.dano,'equipamentos[arma_secundaria][dano]')}</div>${repeater('itens',items)}</div>
 <div class="form-section"><h4>Características</h4>${area('Personalidade',ch.personalidade,'caracteristicas[personalidade]')}${area('Gostos',ch.gostos,'caracteristicas[gostos]')}${area('Desgostos',ch.desgostos,'caracteristicas[desgostos]')}${area('Objetivos',ch.objetivos,'caracteristicas[objetivos]')}${area('Medos',ch.medos,'caracteristicas[medos]')}${area('Histórico',ch.historico,'caracteristicas[historico]')}</div>
 <div class="actions"><button class="btn" type="submit">${esc(submit)}</button></div></form>`;
}
function conceptForm(f={},submit='SALVAR FICHA'){
 const i=f.info||{},a=f.atributos||{},r=f.recursos||{};
 return `<form id="fichaForm" data-tipo="conceito">${imageSection(f,'Imagem do Conceito')}<div class="form-section"><h4>Informações básicas</h4><div class="form-row">${field('Nome',i.nome,'info[nome]','text',true)}${select('Categoria',i.categoria,'info[categoria]',C.CATEGORIAS)}${select('Classe de ameaça',i.classe_ameaca,'info[classe_ameaca]',C.CLASSES_AMEACA)}${field('Origem',i.origem,'info[origem]')}</div></div>${numeric('Atributos',C.ATTRS,a,'atributos')}${numeric('Recursos de combate',['HP','CP','DEF','MOV'],r,'recursos')}<div class="form-section"><h4>Poderes próprios</h4>${repeater('poderes',f.poderes||[])}</div><div class="form-section"><h4>Fraquezas</h4>${repeater('fraquezas',f.fraquezas||[])}</div><div class="form-section"><h4>Resistências</h4>${repeater('resistencias',f.resistencias||[])}</div><div class="form-section"><h4>Influência Conceitual</h4><textarea name="influencia_conceitual">${esc(f.influencia_conceitual||'')}</textarea></div><div class="form-section"><h4>Conceitos Absorvidos</h4>${repeater('absorvidos',f.absorvidos||[])}</div><div class="form-section"><h4>Visibilidade</h4><label class="checkbox-row"><input type="checkbox" name="visivel_jogadores"${f.visivel_jogadores?' checked':''}> Visível para os Jogadores</label><p class="empty-hint" style="margin-top:6px;display:block">Desmarcado, só o Mestre vê esta ficha — útil pra não entregar spoiler de um Conceito inimigo antes da hora.</p></div><div class="actions"><button class="btn" type="submit">${esc(submit)}</button></div></form>`;
}
function parseRepeater(form,g){return [...form.querySelectorAll(`#rep_${g} .repeater-row`)].map(r=>{const o={};C.REPEATER_FIELDS[g].forEach(([k])=>{const el=r.querySelector(`[name^="${g}["][name$="[${k}]"]`);o[k]=(el?.value||'').trim()});return o}).filter(o=>Object.values(o).some(Boolean))}
function num(v){return String(v??'').trim()===''?null:Number.isFinite(Number(v))?Number(v):null}
function build(form,tipo,oldImage=null){const fd=new FormData(form),f={codigo:null,tipo,imagem:oldImage};
 if(tipo==='hunter'){f.usuario_id=(fd.get('usuario_id')||'')!==''?Number(fd.get('usuario_id')):null;f.info={};['nome','apelido','idade','sexo','altura','organizacao','rank','ocupacao'].forEach(k=>f.info[k]=String(fd.get(`info[${k}]`)||'').trim());f.atributos={};C.ATTRS.forEach(k=>f.atributos[k]=num(fd.get(`atributos[${k}]`)));f.recursos={};['HP','SP','CP','DEF','MOV'].forEach(k=>f.recursos[k]=num(fd.get(`recursos[${k}]`)));f.pericias={};C.PERICIAS.forEach(k=>f.pericias[k]=fd.has(`pericias[${k}]`));['contratos','tecnicas'].forEach(g=>f[g]=parseRepeater(form,g));f.equipamentos={arma_principal:{nome:String(fd.get('equipamentos[arma_principal][nome]')||''),dano:String(fd.get('equipamentos[arma_principal][dano]')||'').trim()},arma_secundaria:{nome:String(fd.get('equipamentos[arma_secundaria][nome]')||''),dano:String(fd.get('equipamentos[arma_secundaria][dano]')||'').trim()},itens:parseRepeater(form,'itens').map(x=>x.nome)};f.caracteristicas={};['personalidade','gostos','desgostos','objetivos','medos','historico'].forEach(k=>f.caracteristicas[k]=String(fd.get(`caracteristicas[${k}]`)||'').trim());}
 else {f.info={};['nome','categoria','classe_ameaca','origem'].forEach(k=>f.info[k]=String(fd.get(`info[${k}]`)||'').trim());f.atributos={};C.ATTRS.forEach(k=>f.atributos[k]=num(fd.get(`atributos[${k}]`)));f.recursos={};['HP','CP','DEF','MOV'].forEach(k=>f.recursos[k]=num(fd.get(`recursos[${k}]`)));['poderes','fraquezas','resistencias','absorvidos'].forEach(g=>f[g]=parseRepeater(form,g));f.influencia_conceitual=String(fd.get('influencia_conceitual')||'').trim();f.visivel_jogadores=fd.has('visivel_jogadores');}
 return f;}
function fileData(file){return new Promise((res,rej)=>{if(!file||!file.size)return res(null);if(file.size>5*1024*1024)return rej(new Error('Imagem maior que 5MB.'));const ok=['image/jpeg','image/png','image/gif','image/webp'];if(!ok.includes(file.type))return rej(new Error('Formato de imagem não aceito.'));const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(new Error('Falha ao ler imagem.'));r.readAsDataURL(file)})}
function initRepeaters(root){let seq=Date.now();root.querySelectorAll('.repeater-add').forEach(btn=>btn.addEventListener('click',()=>{const g=btn.dataset.add;document.getElementById(`rep_${g}`).insertAdjacentHTML('beforeend',row(g,{},seq++));}));root.addEventListener('click',e=>{if(e.target.closest('.repeater-remove'))e.target.closest('.repeater-row').remove()});root.querySelector('#armaPrincipal')?.addEventListener('change',e=>{const a=C.ARMAS.find(x=>x.nome===e.target.value);const input=root.querySelector('[name="equipamentos[arma_principal][dano]"]');if(input)input.value=a?.dano||''});root.querySelector('#armaSecundaria')?.addEventListener('change',e=>{const a=C.ARMAS.find(x=>x.nome===e.target.value);const input=root.querySelector('[name="equipamentos[arma_secundaria][dano]"]');if(input)input.value=a?.dano||''});}
function view(f){
 const i=f.info||{},a=f.atributos||{},r=f.recursos||{};
 let html=f.imagem?`<img src="${esc(f.imagem)}" class="ficha-img" alt="Imagem da ficha">`:'';
 const stats=(keys,data)=>`<div class="sheet-grid">${keys.map(k=>`<div class="stat"><small>${k}</small><strong>${data?.[k]??'—'}</strong></div>`).join('')}</div>`;
 if(f.tipo==='hunter'){
   const skillBadges=C.PERICIAS.filter(x=>f.pericias?.[x]).map(x=>`<span class="badge">${esc(x)} +3</span>`).join('')||'Nenhuma registrada';
   html+=`<p class="sheet-meta">${esc(i.apelido||'')}${i.apelido?' • ':''}${esc(i.rank||'—')} • ${esc(i.organizacao||'Sem organização')}</p><span class="section-label">Informações</span><p class="view-text">Idade: ${esc(i.idade||'—')} • Sexo: ${esc(i.sexo||'—')} • Altura: ${esc(i.altura||'—')} • Ocupação: ${esc(i.ocupacao||'—')}</p><span class="section-label">Atributos</span>${stats(C.ATTRS,a)}<span class="section-label">Recursos</span>${stats(['HP','SP','CP','DEF','MOV'],r)}<span class="section-label">Perícias</span><p class="view-text">${skillBadges}</p>${entries('Contratos',f.contratos,'conceito','beneficios')}${entries('Técnicas próprias',f.tecnicas,'nome','descricao')}${entries('Equipamentos',((f.equipamentos?.itens||[]).map(x=>({nome:x}))), 'nome','')}${entries('Características',[{nome:'Personalidade',descricao:f.caracteristicas?.personalidade},{nome:'Gostos',descricao:f.caracteristicas?.gostos},{nome:'Desgostos',descricao:f.caracteristicas?.desgostos},{nome:'Objetivos',descricao:f.caracteristicas?.objetivos},{nome:'Medos',descricao:f.caracteristicas?.medos},{nome:'Histórico',descricao:f.caracteristicas?.historico}],'nome','descricao')}`;
 } else {
   const threat=i.classe_ameaca||'?';
   html+=`<p class="sheet-meta"><span class="badge threat-${esc(threat)}">${esc(threat)}</span> ${esc(i.categoria||'—')} • Origem: ${esc(i.origem||'—')} ${!f.visivel_jogadores?'<span class="badge hidden-flag">OCULTO PARA JOGADORES</span>':''}</p><span class="section-label">Atributos</span>${stats(C.ATTRS,a)}<span class="section-label">Recursos de combate</span>${stats(['HP','CP','DEF','MOV'],r)}${entries('Poderes próprios',f.poderes,'nome','descricao')}${entries('Fraquezas',f.fraquezas,'nome','descricao')}${entries('Resistências',f.resistencias,'nome','descricao')}<span class="section-label">Influência Conceitual</span><p class="view-text">${esc(f.influencia_conceitual||'—')}</p>${entries('Conceitos Absorvidos',f.absorvidos,'nome','detalhe')}`;
 }
 return html;
}
function entries(title,items=[],nameKey='nome',descKey='descricao'){return `<span class="section-label">${title}</span>${items?.length?items.map(x=>`<div class="entry-block"><strong>${esc(x[nameKey]||'')}</strong>${descKey&&x[descKey]?`<span>${esc(x[descKey])}</span>`:''}</div>`).join(''):'<div class="empty-hint">Nenhum registro</div>'}`}
window.FichaForms={hunterForm,conceptForm,build,fileData,initRepeaters,view};
})();
